### ISSUE TITLE
The organization of repository.

### ISSUE THREAD

**Issue by ghost** [icc2115/nonlinear-gc#1]
Hi,
Is this the repository for [this](https://arxiv.org/abs/1802.05842) paper? Can you please explain the organisation of the repository. Where exactly have you implemented the cMLP and cLSTM? Thanks for taking the time.

**Comment by iancovert** [comment]
Hi Avinash. Yes, this is the codebase used for the experiments described in that paper. I apologize for the organization of the repo and the code style, it's not ideal and I've been meaning to write a cleaner implementation.

But until I get around to that, I think I can point you towards a couple useful files. The implementation of the cMLP and cLSTM are in Model/mlp.py and Model/lstm.py, with functions for the proximal step (a key step in the optimization algorithm) implemented in Model/regularize.py.

If you want to see how one of the experiments works, you could check out Experiments/standardized_var_mlp_encoding.py. (Some of the file names, like this one, may seem confusing given the terminology we settled on for the paper.)

You probably get the idea of the repo's organization by now: basically, the different models we played with are implemented in Model, and the various experiments are in Experiments. (The Jobs directory will be useless to you, I just used it to set up jobs on our cluster.)

Hopefully that helps. Let me know if you have any other questions, I'd be happy to help you get one of these models working.

**Comment by ghost** [comment]
Thanks, Ian, that was very clear.
